
# Base directories - change these to switch datasets
base_data_dir: "/mnt/data/ML-Ready/mixed_data"  # Change this line for different datasets
base_checkpoint_dir: "/mnt/data/ML-Ready/mixed_data"    # Change this line for different datasets

# Model configuration
selected_model: "ViT"  # Options: "cnn", "vit",
batch_size:    64
epochs:        100
megsai:
  architecture:
    "cnn"
  seed:
    42
  lr:
    0.00001
  cnn_model:
    "resnet"
  cnn_dp:
    0.5

#vit:
#    embed_dim: 256
#    num_channels: 6  # AIA has 6 channels
#    num_classes: 1  # Regression task, predicting SXR flux
#    patch_size: 32
#    num_patches: 256
#    hidden_dim: 256
#    num_heads: 1
#    num_layers: 1
#    dropout: 0.25
#    lr: .0001


vit:
    embed_dim: 512
    num_channels: 6  # AIA has 6 channels
    num_classes: 1  # Regression task, predicting SXR flux
    patch_size: 32
    num_patches: 256
    hidden_dim: 512
    num_heads: 4
    num_layers: 4
    dropout: 0.25
    lr: .0001



# Data paths (automatically constructed from base directories)
data:
  aia_dir:
    "${base_data_dir}/AIA"
  sxr_dir:
    "${base_data_dir}/SXR"
  sxr_norm_path:
    "${base_data_dir}/SXR/normalized_sxr.npy"
  checkpoints_dir:
    "${base_checkpoint_dir}/checkpoints"

wandb:
  entity: jayantbiradar619-university-of-arizona # Use your exact W&B username
  project: MEGS-AI ViT Testing Griffin
  job_type: training
  tags:
    - aia
    - sxr
    - regression
  wb_name: mixed-vit-aia-sxr-regression
  notes: Regression from AIA images (6 channels) to GOES SXR flux