
  model:
    architecture:
      - hybrid
    seed:
      - 42
    lr:
      - 0.0001
    cnn_model:
      - resnet
    cnn_dp:
      - 0.75
    epochs:
      - 1
    save_dictionary:
      -
  wandb:
    entity: jayantbiradar619-university-of-arizona # Use your exact W&B username
    project: MEGS-AI flaring  # Lowercase, no spaces
    job_type: training
    tags:
      - aia
      - sxr
      - regression
    name: flaring_100epoch
    notes: Regression from AIA images (6 channels) to GOES SXR flux