
  model:
    architecture:
      - hybrid
    seed:
      - 42
    lr:
      - 0.00001
    cnn_model:
      - resnet
    cnn_dp:
      - 0.75
    epochs:
      - 75

  wandb:
    entity: jayantbiradar619-university-of-arizona # Use your exact W&B username
    project: MEGS-AI flaring  # Lowercase, no spaces
    job_type: training
    tags:
      - aia
      - sxr
      - regression
    wb_name: non-flaring-baseline-hybrid-v1
    notes: Regression from AIA images (6 channels) to GOES SXR flux