
# Base directories - change these to switch datasets
base_data_dir: "/mnt/data/ML-Ready/non_flares_event_dir"  # Change this line for different datasets
base_checkpoint_dir: "/mnt/data/ML-Ready/non_flares_event_dir"    # Change this line for different datasets

# Model configuration
model:
  architecture:
    "hybrid"
  seed:
    42
  lr:
    0.00001
  cnn_model:
    "resnet"
  cnn_dp:
    0.75
  epochs:
    100
  batch_size:
    64

# Data paths (automatically constructed from base directories)
data:
  aia_dir:
    "${base_data_dir}/AIA"
  sxr_dir:
    "${base_data_dir}/SXR"
  sxr_norm_path:
    "${base_data_dir}/SXR/normalized_sxr.npy"
  checkpoints_dir:
    "${base_checkpoint_dir}/checkpoints"

wandb:
  entity: jayantbiradar619-university-of-arizona # Use your exact W&B username
  project: MEGS-AI flaring  # Lowercase, no spaces
  job_type: training
  tags:
    - aia
    - sxr
    - regression
  wb_name: non_flaring-baseline-v2-lr-scheduler
  notes: Regression from AIA images (6 channels) to GOES SXR flux