
#Base directories - change these to switch datasets
base_data_dir: "/mnt/data/ML-Ready_clean/mixed_data"  # Change this line for different datasets
base_checkpoint_dir: "/mnt/data/ML-Ready_clean/mixed_data"    # Change this line for different datasets

# Model configuration
selected_model: "hybrid"  # Options: "cnn", "vit",
batch_size:    64
epochs:        150
megsai:
  architecture: "cnn"
  seed: 42
  lr: 0.0001
  cnn_model: "resnet"
  cnn_dp: 0.2

#vit:
#    embed_dim: 256
#    num_channels: 6  # AIA has 6 channels
#    num_classes: 1  # Regression task, predicting SXR flux
#    patch_size: 32
#    num_patches: 256
#    hidden_dim: 256
#    num_heads: 1
#    num_layers: 1
#    dropout: 0.25
#    lr: .0001


vit_custom:
    embed_dim: 512
    num_channels: 6
    num_classes: 1
    patch_size: 16
    num_patches: 1024
    hidden_dim: 512
    num_heads: 8
    num_layers: 6
    dropout: 0.2
    lr: 0.0001





# Data paths (automatically constructed from base directories)
data:
  aia_dir:
    "${base_data_dir}/AIA"
  sxr_dir:
    "${base_data_dir}/SXR"
  sxr_norm_path:
    "${base_data_dir}/SXR/normalized_sxr.npy"
  checkpoints_dir:
    "${base_checkpoint_dir}/checkpoints"

wandb:
  entity: jayantbiradar619-university-of-arizona # Use your exact W&B username
  project: MEGS-AI Baseline
  job_type: training
  tags:
    - aia
    - sxr
    - regression
  wb_name: baseline-test
  notes: Regression from AIA images (6 channels) to GOES SXR flux