# Base directories - change these to switch datasets
base_data_dir: "/mnt/data2/non_flares_event_dir"  # Change this line for different datasets
output_path: "${base_data_dir}/output/deep-vit8000-1.csv"
checkpoint: "/ViT-final-20250726_000801.pt"
# Data paths (automatically constructed from base directories)
data:
  aia_dir:
    "${base_data_dir}/AIA"
  sxr_dir:
    "${base_data_dir}/SXR"
  sxr_norm_path:
    "${base_data_dir}/SXR/normalized_sxr.npy"
  checkpoint_path:
    "${base_data_dir}/checkpoints/${checkpoint}"


