# Inference Configuration
base_data_dir: "/mnt/data3/ML-Ready_clean/non_flares_event_dir/"
base_checkpoint_dir: "/mnt/data3/ML-Ready_clean/non_flares_event_dir/checkpoints"

# Model paths
model_path: "${base_checkpoint_dir}/ViT-seq2seq-final-20250804_160032.pt"

# Data paths
data:
  aia_dir: "${base_data_dir}/AIA/test/"
  sxr_dir: "${base_data_dir}/SXR/test/"
  sxr_norm_path: "${base_data_dir}/SXR/normalized_sxr.npy"

# Inference settings
inference:
  num_samples: 100
  output_dir: "./inference_results"