# Base directories - change these to switch datasets
base_data_dir: "/mnt/data/ML-Ready-mixed/ML-Ready-mixed"  # Change this line for different datasets
output_path: "${base_data_dir}/output/4-wavelengths.csv"
weight_path: "${base_data_dir}/4-wavelengths/"
mc:
  active: "true"
  runs: 5
# Enable or disable MC Dropout
# Data paths (automatically constructed from base directories)
SolO: "false"
SolO_data:
    solo_img_dir: "/mnt/data/ML-Ready_clean/SolO/SolO/ML-Ready-SolO"
    sxr_dir: "${base_data_dir}/SXR"
    sxr_norm_path: "${base_data_dir}/SolO/SXR/normalized_sxr.npy"
model: "vit"  # Options: "cnn", "vit", "ViT Custom"
wavelengths: [131, 193, 211, 304]  # AIA wavelengths in Angstroms
data:
  aia_dir:
    "${base_data_dir}/AIA"
  sxr_dir:
    "${base_data_dir}/SXR"
  sxr_norm_path:
    "${base_data_dir}/SXR/normalized_sxr.npy"
  checkpoint_path:
    "/mnt/data/ML-Ready-mixed/ML-Ready-mixed/new-checkpoint/vit-patch-size-16-4-wavelengths-lower-weights-oversampling-epoch=213-val_loss=0.0583.ckpt"

