# Base directories - change these to switch datasets
base_data_dir: "/mnt/data/ML-Ready_clean/mixed_data"  # Change this line for different datasets
output_path: "${base_data_dir}/output/final-model-results.csv"
checkpoint: "${base_data_dir}/checkpoints/"
weight_path: "${base_data_dir}/weights-84epoch/"
# Data paths (automatically constructed from base directories)
model: "hybrid"  # Options: "cnn", "vit", "ViT Custom"
data:
  aia_dir:
    "${base_data_dir}/AIA"
  sxr_dir:
    "${base_data_dir}/SXR"
  sxr_norm_path:
    "${base_data_dir}/SXR/normalized_sxr.npy"
  checkpoint_path:
    "/mnt/data/ML-Ready_clean/mixed_data/checkpoints/baseline-test-final-20250730_091211.pth"

