# Base directories - change these to switch datasets
base_data_dir: "/mnt/data/ML-Ready/mixed_data"  # Change this line for different datasets
output_path: "${base_data_dir}/outputs/deep-vit-weighted.csv"
checkpoint: "mixed-vit-deep-model-epoch=19-val_loss=0.1484.pth"
weight_path: "${base_data_dir}/weights/"
# Data paths (automatically constructed from base directories)
data:
  aia_dir:
    "${base_data_dir}/AIA"
  sxr_dir:
    "${base_data_dir}/SXR"
  sxr_norm_path:
    "${base_data_dir}/SXR/normalized_sxr.npy"
  checkpoint_path:
    #"${base_data_dir}/checkpoints/${checkpoint}"
    "/home/griffingoodwin/2025-HL-Flaring-MEGS-AI/flaring/forecasting/training/MEGS-AI ViT Testing Griffin/hztj5skd/checkpoints/epoch=89-step=101250.ckpt"

